# stationarity_diag.r
# Stationarity / validity diagnostics
# Two distinct notions of stationarity (do not conflate):
#   * spatial (simultaneous) invertibility:  min_i det(I_k − ω_i·M) > 0
#     for M = R and Λ — this is what spectral_radius() measures.
#   * temporal (coupled) stationarity:  ρ(M_dyn) < 1 where
#     M_dyn = (I − R⊗W)^{-1}(A⊗I).  Because row-standardized W always has
#     eigenvalue ω = 1, the block (I_k − R)^{-1}A is usually binding.
# The real-data-approximation parameter set is EXPLOSIVE (ρ(M_dyn) ≈ 1.07 for
# 1111; ≈1.026/1.023 for 0111/1011): for those cells data are generated by a
# single conditional transition and check_estimate_validity must be
# called with check_temporal = FALSE.

#' min_i det(I_k − ω_i·M) over the eigenvalues of W
#'
#' Positive value <=> I − M⊗W is invertible along the spatial spectrum
#' (sufficient sign-based criterion used throughout this project).
#'
#' @param M k×k spatial coefficient matrix
#' @param eigen_W eigenvalues of W
#' @return minimum polynomial value (positive = inside the spatial region)
spatial_det_min <- function(M, eigen_W) {
  e <- compute_elem_sym_poly(M, verbose = FALSE)
  min(.poly_values_spatial(e, eigen_W, nrow(M)))
}

#' Temporal (coupled) spectral radius ρ(M_dyn) = ρ[(I − R⊗W)^{-1}(A⊗I)]
#'
#' Computed blockwise over the eigenvalues of W:
#' ρ(M_dyn) = max_i ρ[(I_k − ω_i R)^{-1} A].  < 1 means the time recursion is
#' stationary; ≥ 1 means it diverges (burn-in impossible).
#'
#' @param R k×k spatial lag matrix (0 matrix if the DGP has no spatial lag)
#' @param A k×k temporal AR matrix
#' @param eigen_W eigenvalues of W
#' @return spectral radius (scalar)
temporal_spectral_radius <- function(R, A, eigen_W) {
  k <- nrow(A)
  I_k <- diag(k)
  rho_max <- 0
  for (omega in eigen_W) {
    Mblk <- tryCatch(solve(I_k - omega * R, A), error = function(e) NULL)
    if (is.null(Mblk)) return(Inf)  # singular block: outside the spatial region
    rho <- max(Mod(eigen(Mblk, only.values = TRUE)$values))
    if (rho > rho_max) rho_max <- rho
  }
  rho_max
}

#' Post-estimation validity diagnostics for one fitted model
#'
#' Records the determinant/stationarity diagnostics that the optimizer
#' (smooth = TRUE) does not enforce, so invalid convergence points can be
#' flagged and excluded from Monte Carlo aggregation.
#'
#' @param result build_result_object() output (needs $coefficients, $model_type)
#' @param data_list the data_list used for the fit (needs eigen_W, X, k, n)
#' @param check_temporal apply the ρ(M_dyn) < 1 criterion. Set FALSE for the
#'        real-data-approximation cells, whose TRUE parameters violate it
#'        (conditional single-transition DGP); rho_dyn is still recorded.
#' @return list(min_det_R, min_det_Lambda, det_Sigma, det_XtSinvX,
#'              rho_dyn, stationarity_ok)
check_estimate_validity <- function(result, data_list, check_temporal = TRUE) {

  k <- data_list$k
  n <- data_list$n
  eigen_W <- data_list$eigen_W
  coefs <- result$coefficients

  R_hat      <- coefs$R
  Lambda_hat <- coefs$Lambda
  Sigma_hat  <- coefs$Sigma

  # A is not stored separately: the lag coefficients are the LAST k² entries of
  # β (build_design_matrix_extended appends the y_lag block, row-major α_ij)
  A_hat <- NULL
  include_lag <- isTRUE(data_list$data_info$include_time_lag)
  if (include_lag && !is.null(coefs$beta) && length(coefs$beta) >= k^2) {
    A_hat <- matrix(utils::tail(as.numeric(coefs$beta), k^2), k, k, byrow = TRUE)
  }

  # Spatial invertibility (only for matrices the model actually estimates)
  min_det_R <- if (!is.null(R_hat)) spatial_det_min(R_hat, eigen_W) else NA_real_
  min_det_Lambda <- if (!is.null(Lambda_hat)) spatial_det_min(Lambda_hat, eigen_W) else NA_real_

  # Σ positive definiteness via its determinant and smallest eigenvalue
  det_Sigma <- if (!is.null(Sigma_hat)) det(Sigma_hat) else NA_real_
  sigma_pd <- !is.null(Sigma_hat) &&
    min(eigen(Sigma_hat, symmetric = TRUE, only.values = TRUE)$values) > 0

  # Design-information determinant det(X'(Σ⁻¹⊗I)X) > 0
  det_XtSinvX <- NA_real_
  if (!is.null(Sigma_hat) && sigma_pd) {
    Sigma_inv <- solve(Sigma_hat)
    X <- data_list$X
    XtSX <- matrix(0, ncol(X), ncol(X))
    for (i in 1:k) {
      for (j in 1:k) {
        i_idx <- ((i - 1) * n + 1):(i * n)
        j_idx <- ((j - 1) * n + 1):(j * n)
        XtSX <- XtSX + Sigma_inv[i, j] *
          t(X[i_idx, , drop = FALSE]) %*% X[j_idx, , drop = FALSE]
      }
    }
    det_XtSinvX <- det(XtSX)
    # guard against overflow to Inf for large matrices: use sign of log-det
    if (!is.finite(det_XtSinvX)) {
      ld <- determinant(XtSX, logarithm = TRUE)
      det_XtSinvX <- ifelse(ld$sign > 0, .Machine$double.xmax, -1)
    }
  }

  # Temporal coupled spectral radius (recorded regardless of check_temporal)
  rho_dyn <- NA_real_
  if (!is.null(A_hat)) {
    R_for_dyn <- if (!is.null(R_hat)) R_hat else matrix(0, k, k)
    rho_dyn <- temporal_spectral_radius(R_for_dyn, A_hat, eigen_W)
  }

  ok <- TRUE
  if (!is.null(R_hat))      ok <- ok && is.finite(min_det_R) && min_det_R > 0
  if (!is.null(Lambda_hat)) ok <- ok && is.finite(min_det_Lambda) && min_det_Lambda > 0
  ok <- ok && sigma_pd
  ok <- ok && is.finite(det_XtSinvX) && det_XtSinvX > 0
  if (check_temporal && !is.null(A_hat)) ok <- ok && is.finite(rho_dyn) && rho_dyn < 1

  list(
    min_det_R      = min_det_R,
    min_det_Lambda = min_det_Lambda,
    det_Sigma      = det_Sigma,
    det_XtSinvX    = det_XtSinvX,
    rho_dyn        = rho_dyn,
    stationarity_ok = ok
  )
}
